### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by rsubbaraman** [ucsdwcsng/sparsdr.cpp#4]
- [x] Fix staggered buffer - write tests
- [x] verify e2e reconstruction
- [x] build out SparSDR filter function - FFT filter-based compression
- [x] v0.1.0 release
- [ ] Implement encoder and parser
- [ ] TBD
